# Configure this Discovery Server
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client: 
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: 8080   
